// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4u0o1USMGMXtYjOUKLxkaOGF4dJG-MjI',
    appId: '1:920760236789:web:4a093a3e73469d267d63bc',
    messagingSenderId: '920760236789',
    projectId: 'malibrairie-2aa2a',
    authDomain: 'malibrairie-2aa2a.firebaseapp.com',
    storageBucket: 'malibrairie-2aa2a.firebasestorage.app',
    measurementId: 'G-LSCYFRT4KG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV1vTAj4iZvvZ_jig1_mYVWDRYR4nOcXs',
    appId: '1:920760236789:android:4ae6592318e8d1bf7d63bc',
    messagingSenderId: '920760236789',
    projectId: 'malibrairie-2aa2a',
    storageBucket: 'malibrairie-2aa2a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf1OWv2HT5Bmq-mH-Ptz6I981zhWMoEvE',
    appId: '1:920760236789:ios:a5583e3cfcc630307d63bc',
    messagingSenderId: '920760236789',
    projectId: 'malibrairie-2aa2a',
    storageBucket: 'malibrairie-2aa2a.firebasestorage.app',
    iosBundleId: 'com.example.malibrairie',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf1OWv2HT5Bmq-mH-Ptz6I981zhWMoEvE',
    appId: '1:920760236789:ios:a5583e3cfcc630307d63bc',
    messagingSenderId: '920760236789',
    projectId: 'malibrairie-2aa2a',
    storageBucket: 'malibrairie-2aa2a.firebasestorage.app',
    iosBundleId: 'com.example.malibrairie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4u0o1USMGMXtYjOUKLxkaOGF4dJG-MjI',
    appId: '1:920760236789:web:e07007f3e5dddf047d63bc',
    messagingSenderId: '920760236789',
    projectId: 'malibrairie-2aa2a',
    authDomain: 'malibrairie-2aa2a.firebaseapp.com',
    storageBucket: 'malibrairie-2aa2a.firebasestorage.app',
    measurementId: 'G-Q2R56WBQS9',
  );
}
